### ISSUE TITLE
Samson algorithm code?

### ISSUE THREAD

**Issue by Zireael07** [kraken-robotics/The-Kraken-Pathfinding#7]
The moon rover repo is archived now and I can't figure out how they implemented it, and the README only explains the basic terms, not how the algorithm steers.

**Comment by PFGimenez** [comment]
The revelant file in the moon rover repo is this one: https://github.com/INTechSenpai/moon-rover/blob/master/teensy/loli_teensy/MotionControlSystem.cpp.
Check the function `void MotionControlSystem::control()`.
I didn’t code that part so I won’t be able to help much however.

**Comment by Zireael07** [comment]
Thanks - I can't read French so I was mostly stumbling around :P
